version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
  - artkirienko
  assignees:
  - artkirienko
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 4.1.1
  - dependency-name: ffi
    versions:
    - 1.14.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
  - artkirienko
  assignees:
  - artkirienko
